version: '3.9'

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=churko.settings
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8008:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    ports:
      - "8080:80"   # HTTP нестандартный порт
      - "446:443"   # HTTPS нестандартный порт
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/var/lib/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    entrypoint: ""
    command: >
      certbot certonly --webroot 
      --webroot-path=/var/www/certbot 
      --email your-email@example.com 
      --agree-tos 
      --no-eff-email 
      -d churko.daskoro.site -d www.churko.daskoro.site


volumes:
  postgres_data:
  static_volume:
  certs-data:
